# Generated by Django 4.2.9 on 2025-08-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('detachment', models.CharField(max_length=50)),
                ('front_elevation_photos', models.JSONField(default=list)),
                ('other_views', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('glass_type', models.CharField(max_length=50)),
                ('frame_type', models.CharField(max_length=50)),
                ('frame_colour', models.CharField(max_length=50)),
                ('sill_type', models.CharField(max_length=50)),
                ('sill_colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=255)),
                ('openers', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=50)),
                ('skirting_type', models.CharField(max_length=50)),
                ('skirting_colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=255)),
                ('sign_of_leakages', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gas', 'Gas'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Heat', 'Heat'), ('Other', 'Other')], max_length=20)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('photo_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tested', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_appliances', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspectors', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Furnishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnishings', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnishings', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('additions', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('light_switches', models.PositiveIntegerField(default=0)),
                ('plug_sockets', models.PositiveIntegerField(default=0)),
                ('radiators', models.PositiveIntegerField(default=0)),
                ('light_fittings', models.PositiveIntegerField(default=0)),
                ('light_tested', models.BooleanField(default=False)),
                ('plug_sockets_tested', models.BooleanField(default=False)),
                ('electric_switches_safe', models.BooleanField(default=False)),
                ('plug_sockets_safe', models.BooleanField(default=False)),
                ('toilets', models.PositiveIntegerField(default=0)),
                ('basins', models.PositiveIntegerField(default=0)),
                ('base_unit_doors', models.PositiveIntegerField(default=0)),
                ('wall_units', models.PositiveIntegerField(default=0)),
                ('worktops', models.PositiveIntegerField(default=0)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_fittings', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_surfaces', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_features', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('finish', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('frame_type', models.CharField(max_length=50)),
                ('frame_colour', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='DetectorCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_compliance', models.BooleanField()),
                ('solid_fuel_device', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detector_compliance', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Smoke', 'Smoke'), ('CO', 'CO')], max_length=10)),
                ('working', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupboards', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_standard', to='dyn_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('fittings', models.CharField(max_length=255)),
                ('recessed_spotlights', models.PositiveIntegerField()),
                ('bulbs_not_working', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceilings', to='dyn_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='dyn_api.property')),
            ],
        ),
    ]
