# Generated by Django 4.2.9 on 2025-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inspectedBy',
            field=models.CharField(default='Owner', max_length=100),
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
    ]
