# Generated by Django 4.2.9 on 2025-08-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullPropertyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundaries', models.ManyToManyField(blank=True, to='dyn_api.boundary')),
                ('cleaning_standards', models.ManyToManyField(blank=True, to='dyn_api.cleaningstandard')),
                ('detector_compliances', models.ManyToManyField(blank=True, to='dyn_api.detectorcompliance')),
                ('detectors', models.ManyToManyField(blank=True, to='dyn_api.detector')),
                ('documents', models.ManyToManyField(blank=True, to='dyn_api.document')),
                ('external_features', models.ManyToManyField(blank=True, to='dyn_api.externalfeature')),
                ('external_surfaces', models.ManyToManyField(blank=True, to='dyn_api.externalsurface')),
                ('inspectors', models.ManyToManyField(blank=True, to='dyn_api.inspector')),
                ('keys', models.ManyToManyField(blank=True, to='dyn_api.key')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_report', to='dyn_api.property')),
                ('rooms', models.ManyToManyField(blank=True, to='dyn_api.room')),
                ('tenants', models.ManyToManyField(blank=True, to='dyn_api.tenant')),
                ('utilities', models.ManyToManyField(blank=True, to='dyn_api.utility')),
            ],
            options={
                'verbose_name': 'Full Property Report',
                'verbose_name_plural': 'Full Property Reports',
            },
        ),
    ]
