# Generated by Django 4.2.9 on 2026-01-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_type', models.CharField(choices=[('smoke', 'Smoke detector'), ('co', 'CO detector')], max_length=10)),
                ('present', models.BooleanField(help_text='True/False if a detector is present (null = unknown)', null=True)),
                ('working', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.JSONField(blank=True, default=list)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to='dyn_api.property')),
            ],
            options={
                'unique_together': {('property', 'detector_type', 'location')},
            },
        ),
        migrations.RemoveField(
            model_name='smokedetector',
            name='property',
        ),
        migrations.DeleteModel(
            name='CoDetector',
        ),
        migrations.DeleteModel(
            name='SmokeDetector',
        ),
    ]
