# Generated by Django 4.2.9 on 2025-08-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0002_fullpropertyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullPropertyReport',
        ),
    ]
