# Generated by Django 4.2.9 on 2026-01-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0002_detector_remove_smokedetector_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectorcompliance',
            name='detectorCompliance',
        ),
        migrations.RemoveField(
            model_name='detectorcompliance',
            name='solidFuelDevice',
        ),
        migrations.AddField(
            model_name='detectorcompliance',
            name='carbon_monoxide_compliance',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='detectorcompliance',
            name='smoke_alarm_compliance',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
