# Generated by Django 4.2.9 on 2026-01-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0003_remove_detectorcompliance_detectorcompliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturefitting',
            name='fixture',
            field=models.CharField(max_length=1000),
        ),
    ]
