# Generated by Django 4.2.9 on 2026-01-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0004_alter_fixturefitting_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='detector_type',
            field=models.CharField(choices=[('smoke', 'Smoke detector'), ('co', 'CO detector')], max_length=10, null=True),
        ),
    ]
