# Generated by Django 4.2.9 on 2026-01-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0005_alter_detector_detector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='electricityMeterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='gasMeterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='heatMeterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='waterMeterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
