# Generated by Django 4.2.9 on 2026-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0006_alter_utility_electricitymeterreading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='otherMeterReading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
