# Generated by Django 4.2.9 on 2026-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0008_alter_boundary_notes_alter_ceiling_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningstandard',
            name='standard',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='detachment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='inspectedBy',
            field=models.CharField(blank=True, default='Owner', max_length=100, null=True),
        ),
    ]
