# Generated by Django 4.2.9 on 2026-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_api', '0009_alter_cleaningstandard_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenappliance',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='openers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
