# Generated by Django 4.2.9 on 2025-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_details', models.JSONField()),
                ('cleaning_standard', models.JSONField()),
                ('inspected_by', models.CharField(max_length=255)),
                ('external_surface_type', models.JSONField()),
                ('external_features', models.JSONField()),
                ('boundary', models.JSONField()),
                ('rooms', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
